services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:2' # can use 2.11.1
    restart: unless-stopped
    container_name: nginx-proxy-manager
    environment:
      TZ: '${DC_TZ}'
      PUID: '${UID:-1000}'
      PGID: '${GID:-1000}'
#      DISABLE_IPV6: 'true'
    ports:
      - '80:80'
      - '8181:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/proxy.conf:/etc/nginx/conf.d/include/proxy.conf
      - ./configs/geoip2_load_modules.conf:/etc/nginx/modules/geoip2.conf
      - ./configs/custom:/data/nginx/custom
      - ./configs/geoip2_db:/data/nginx/geoip2
      
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    networks:
      - nginx-proxy-manager

networks:
  nginx-proxy-manager:
    external: true
