version: '3'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx-proxy-manager
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:8181:81'
      - '0.0.0.0:443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - nginx-proxy-manager
      
networks:
  nginx-proxy-manager:
    external: true
